# Prometheus Grafana

## Requirements

- [ ] [Docker](https://docs.docker.com/engine/install/)
- [ ] [Docker compose](https://docs.docker.com/compose/install/)
- [ ] [Aws cli](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) (for your existing project that will use prometheus)

## Getting started

After install the requirements and clone this repository:
```
cd existing_repo
cd prometeus
```
We gonna configure the prometheus.yml file, replacing 'IP's variables to our IP's in order to connect with your server and the containers) application(s)
If you need yo add a new application, you can make it just adding a new job_name and configuring like the others specifying the port which is exposed.(In this example I have an application called 'application container' running in the port 8081)
```
- job_name: EC2 Docker daemon
  static_configs:
  - targets: ['IP:9323']
- job_name: application container 
  static_configs:
  - targets: ['IP:8081']
```
## Collect Docker metrics with Prometheus
There is a way that you can get your docker's metrics from the daemon to show in prometheus interface, to make it execute:
```
mv ~/prometheus-grafana/docker-daemon.json /etc/docker
```
[See more](https://docs.docker.com/config/daemon/prometheus/)

-Now you can access to this data through the port 9323 
example: ```http://IP:9323/metrics```

## Testing Prometheus (optional)
At this point we could run our containers and execute queries with prometheus to get information but the purpose is use grafana as a client to get a better experience and useful tool. If you wanna try and make sure prometheus is working well:

```
cd ~/prometheus-grafana
docker-compose up -d
docker ps
```
It will show you the containers running, there should be at least:
- prom/prometheus:latest -> port 9090:9090
- prom/node-exporter:latest -> 9100

At this time if everything is ok, you can access through port 9090 in order to get server's information
example: ```http://IP:9090/metrics```

## Access Prometheus
Access to prometheus interface located at ```http://IP:9090```
 - Verify if targets are reachables moving to: Status -> Targets
 - Check if services are "UP"(showed as green flag)
 - Try executing a simple query (go back to home page and inside expression input text)
 example query: ```engine_daemon_container_states_containers{state="running"}```

## Configuring Grafana
By default grafana use sqlite to store configurations and other things. If you wish store that into a real database and persist you need to configurate:

```
cd ~/prometheus-grafana/grafana
nano grafana.ini 
```
Into grafana.ini file search for [database] like the line 77
```
# Either "mysql", "postgres" or "sqlite3", it's your choice
type = sqlite3
host = 127.0.0.1:3306
name = grafana
user = root
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
password =
# Use either URL or the previous fields to configure the database
# Example: mysql://user:secret@host:port/database
url =
```
Save and run docker compose

- Now open url on port: ```3000```

For the first time access using admin:admin credentials and change for a better password.
Check this link to learn about grafana, how to create a dashboard? how to use? make queries etc... 
```https://grafana.com/docs/grafana/latest/getting-started/getting-started/```
Important! make sure the data source is connected by accessing the prometheus dashboard and verifying as previously done in the "Access Prometheus" step.

So, thats it and have fun! 
## Test and Deploy

```
cd ~/prometheus-grafana
docker-compose up -d
```

***
## Configuring metrics in your node js application
type in console inside you root project folder
 ```
npm i prom-client
 ```
 
 In your index start server file paste
 ```
 const client = require('prom-client')

// Create a Registry which registers the metrics
const register = new client.Registry()

// Add a default label which is added to all metrics
register.setDefaultLabels({
  app: 'autorizapp'
})

// Enable the collection of default metrics
client.collectDefaultMetrics({ register })
```
Enable a route
```
app.get('/metrics', async function (req, res) {
  // Return all metrics the Prometheus exposition format
  res.set('Content-Type', register.contentType);
  let metrics = await register.metrics();
  res.send(metrics);
})
```
Accessing to your url app like ```http://IP:APP_PORT/metrics```

## Authors
- [@grijalvamenita](https://gitlab.com/grijalvamenita)


